# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1ae14ba995544003368cb48760259feb28866528a046e29cfbda53054c61b4f71f89422beee571731c4b7238753efa297f6e73152682601f2f5492a1b3c426

test:
  secret_key_base: 83b213cdf3f7be53ccc02e9eed91b296a9d878b9c281feac426a19c3d6b541ba5453cca687c946488586b1070c4aee7b15434377ef47c049b6ce4c8835f270a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
