# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f852cdc023e5e29f7eb106f169d70e8ba9a2d0d2407b009bbf476e558d12b43fe3b4f7ac5e002b9ebabd26bf18186accd70caf1eff9ebe491809503f501619ec

test:
  secret_key_base: d153e33ea67769ff960bfd8541ae1ef145edd81815e8880826a7fdbf320c590f541453340e5284044aabab29a6d0463ed740479af70792dc032a21fc54d35e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
